services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONN=postgres://user:password@db:5432/mydb?sslmode=disable
      - JWT_SECRET=mydevelopmentsecret
      - ML_URL=http://localhost:8080

volumes:
  pgdata:
